name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build com Maven
      run: mvn -B package

    - name: Lint com Checkstyle (se configurado no pom.xml)
      run: mvn checkstyle:check

    - name: Testes Unitários
      run: mvn test

